In [4]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [7]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
y.shape

(150,)

In [9]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [10]:
y = onehot.fit_transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [12]:
X_treinamento.shape

(105, 4)

In [13]:
X_teste.shape

(45, 4)

In [ ]:
import tensorflow as tf
import numpy as np

In [15]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [18]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [19]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [39]:
W = {'oculta': tf.Variable(tf.random_normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_oculta, neuronios_saida]))}

In [40]:
b = {'oculta': tf.Variable(tf.random_normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_saida]))}

In [41]:
xph = tf.placeholder('float', [None, neuronios_entrada])
yph = tf.placeholder('float', [None, neuronios_saida])

In [42]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

In [43]:
modelo = mlp(xph, W, b)

In [48]:
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
otimizador = tf.train.AdamOptimizer(learning_rate = 0.0001).minimize(erro)

In [32]:
batch_size = 8
batch_total = int(len(X_treinamento) / batch_size)
batch_total

13

In [33]:
X_batches = np.array_split(X_treinamento, batch_total)
X_batches

[array([[-0.29484182, -0.8191665 ,  0.25096731,  0.13322594],
        [-0.41600969, -1.51337539,  0.02350449, -0.12972   ],
        [ 1.2803405 ,  0.33784833,  1.10395287,  1.44795564],
        [ 1.03800476,  0.10644536,  0.36469871,  0.26469891],
        [ 1.03800476,  0.10644536,  0.53529583,  0.39617188],
        [-0.7795133 ,  0.80065426, -1.3412724 , -1.31297673],
        [-1.02184904, -1.74477836, -0.26082403, -0.26119297],
        [-1.50652052,  1.26346019, -1.56873522, -1.31297673],
        [-0.05250608, -0.8191665 ,  0.76275864,  0.92206376]]),
 array([[ 0.4321654 , -0.58776353,  0.59216153,  0.79059079],
        [-0.90068117,  1.72626612, -1.2844067 , -1.18150376],
        [ 1.15917263,  0.33784833,  1.21768427,  1.44795564],
        [ 0.31099753, -1.05056946,  1.04708716,  0.26469891],
        [-0.7795133 ,  1.03205722, -1.2844067 , -1.31297673],
        [-0.05250608, -1.05056946,  0.1372359 ,  0.00175297],
        [-0.17367395, -0.58776353,  0.42156442,  0.13322594],
      

In [35]:
X_batches[1]

array([[ 0.4321654 , -0.58776353,  0.59216153,  0.79059079],
       [-0.90068117,  1.72626612, -1.2844067 , -1.18150376],
       [ 1.15917263,  0.33784833,  1.21768427,  1.44795564],
       [ 0.31099753, -1.05056946,  1.04708716,  0.26469891],
       [-0.7795133 ,  1.03205722, -1.2844067 , -1.31297673],
       [-0.05250608, -1.05056946,  0.1372359 ,  0.00175297],
       [-0.17367395, -0.58776353,  0.42156442,  0.13322594],
       [-1.02184904, -0.1249576 , -1.227541  , -1.31297673]])

In [51]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoca in range(3000):
        erro_medio = 0.0
        batch_total = int(len(X_treinamento) / batch_size)
        X_batches = np.array_split(X_treinamento, batch_total)
        y_batches = np.array_split(y_treinamento, batch_total)
        for i in range(batch_total):
            X_batch, y_batch = X_batches[i], y_batches[i]
            _, custo = sess.run([otimizador, erro], feed_dict = {xph: X_batch, yph: y_batch})
            erro_medio += custo / batch_total
        if epoca % 500 == 0:
            print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))
    W_final, b_final = sess.run([W, b])

Época: 1 erro: 2.305130655948932
Época: 501 erro: 0.4310614214493678
Época: 1001 erro: 0.21876929241877335
Época: 1501 erro: 0.1458973860941254
Época: 2001 erro: 0.11324497276487258
Época: 2501 erro: 0.09635000625768533


In [52]:
W_final

{'oculta': array([[-0.5557124 , -1.8534161 ,  0.15347278,  0.9356429 ],
        [-0.30108556,  1.1704956 ,  1.5173255 ,  0.1725314 ],
        [ 3.2615788 , -1.5167435 , -0.01237538,  0.8732984 ],
        [ 1.229192  , -1.5423791 , -0.12267964,  0.34158868]],
       dtype=float32), 'saida': array([[-2.496203 , -1.3808637,  1.4181937],
        [ 2.0235126, -1.6290889, -1.4720006],
        [-0.2312544,  0.5091364, -1.0839738],
        [-0.879805 , -2.9005344,  1.1711245]], dtype=float32)}

In [53]:
b_final

{'oculta': array([-1.5457541, -1.1545649, -2.7522078, -1.791996 ], dtype=float32),
 'saida': array([-1.67663  ,  2.3390503, -0.8624562], dtype=float32)}

In [60]:
# previsões
previsoes_teste = mlp(xph, W_final, b_final)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    r1 = sess.run(previsoes_teste, feed_dict = {xph: X_teste})
    r2 = sess.run(tf.nn.softmax(r1))
    r3 = sess.run(tf.argmax(r2, 1))

In [55]:
r1

array([[ 11.118966  ,  -9.143909  ,  -6.3326015 ],
       [  0.46614596,  -0.56754017,   1.4167739 ],
       [ -7.2883554 ,  -5.4409413 ,   5.9847484 ],
       [ -3.7926512 ,  -3.0121484 ,   3.8610363 ],
       [-11.634445  , -12.16648   ,   9.655673  ],
       [  0.46614596,  -0.56754017,   1.4167739 ],
       [ 12.781762  , -10.482593  ,  -7.542199  ],
       [  0.46614596,  -0.56754017,   1.4167739 ],
       [ -0.43019727,  -1.3685731 ,   2.0108936 ],
       [ -6.5688195 ,  -4.6044903 ,   5.454031  ],
       [ 11.756301  ,  -9.657015  ,  -6.7962294 ],
       [ -1.208863  ,  -1.4941311 ,   2.3684142 ],
       [ -0.45706168,  -1.0782454 ,   1.9412855 ],
       [ -0.04519364,  -0.85040593,   1.7072866 ],
       [  0.46614596,  -0.56754017,   1.4167739 ],
       [ 13.877924  , -11.36509   ,  -8.339601  ],
       [  0.34693587,  -0.960551  ,   1.5754566 ],
       [  0.1385639 ,  -0.74875385,   1.6028866 ],
       [ -0.32761434,  -1.006637  ,   1.8677412 ],
       [ -0.14241233,  -0.90418

In [57]:
r2

array([[1.00000000e+00, 3.27307426e-08, 3.51000295e-08],
       [8.48009288e-02, 6.22998953e-01, 2.92200089e-01],
       [1.29140608e-06, 1.69198102e-04, 9.99829531e-01],
       [3.50388029e-04, 1.57953147e-02, 9.83854234e-01],
       [4.25982860e-10, 5.16823651e-09, 1.00000000e+00],
       [8.48009288e-02, 6.22998953e-01, 2.92200089e-01],
       [1.00000000e+00, 1.62715763e-09, 1.98537808e-09],
       [8.48009288e-02, 6.22998953e-01, 2.92200089e-01],
       [4.10217308e-02, 3.31507504e-01, 6.27470732e-01],
       [4.50634934e-06, 6.63640501e-04, 9.99331772e-01],
       [1.00000000e+00, 1.03591962e-08, 1.16725545e-08],
       [1.55827906e-02, 2.41972312e-01, 7.42444813e-01],
       [3.73779312e-02, 4.14810210e-01, 5.47811866e-01],
       [5.58187105e-02, 5.15337050e-01, 4.28844154e-01],
       [8.48009288e-02, 6.22998953e-01, 2.92200089e-01],
       [1.00000000e+00, 2.24961536e-10, 2.98867514e-10],
       [8.97947475e-02, 5.01680791e-01, 4.08524394e-01],
       [6.55138046e-02, 5.57168

In [61]:
r3

array([0, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2,
       2])

In [66]:
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([0, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2,
       2])

In [67]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, r3)
taxa_acerto

1.0