In [47]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [48]:
base.shape

(21613, 21)

In [49]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [50]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [51]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [52]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [53]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [54]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [55]:
import tensorflow as tf

In [56]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [57]:
colunas

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [58]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a283e3668>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [59]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [60]:
X_treinamento.shape

(15129, 1)

In [61]:
y_treinamento.shape

(15129, 1)

In [62]:
X_teste.shape

(6484, 1)

In [63]:
y_teste.shape

(6484, 1)

In [64]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [65]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [66]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19/model.ckpt.
INFO:tensorflow:loss = 10.2812195, step = 1
INFO:tensorflow:global_step/sec: 935.638
INFO:tensorflow:loss = 16.471153, step = 101 (0.108 sec)
INFO:tensorflow:global_step/sec: 1091.75
INFO:tensorflow:loss = 7.025251, step = 201 (0.092 sec)
INFO:tensorflow:global_step/sec: 1199.18
INFO:tensorflow:loss = 4.3612294, step = 301 (0.083 sec)
INFO:tensorflow:global_step/sec: 1105.98
INFO:tensorflow:loss = 33.310684, step = 401 (0.090 sec)
INFO:tensorflow:global_step/sec: 1093.7
INFO:tensorflow:loss = 11.092807, step = 501 (0.091 sec)
INFO:tensorflow:global_step/sec: 1093.23
INFO:tensorflow:loss = 12.377962, step = 601 (0.091 sec)
INFO:tensorflo

INFO:tensorflow:loss = 18.02789, step = 8001 (0.086 sec)
INFO:tensorflow:global_step/sec: 1185.27
INFO:tensorflow:loss = 8.093042, step = 8101 (0.084 sec)
INFO:tensorflow:global_step/sec: 1158.78
INFO:tensorflow:loss = 9.519501, step = 8201 (0.086 sec)
INFO:tensorflow:global_step/sec: 1161.8
INFO:tensorflow:loss = 17.835548, step = 8301 (0.086 sec)
INFO:tensorflow:global_step/sec: 1285.48
INFO:tensorflow:loss = 16.058996, step = 8401 (0.078 sec)
INFO:tensorflow:global_step/sec: 1257.01
INFO:tensorflow:loss = 29.560345, step = 8501 (0.079 sec)
INFO:tensorflow:global_step/sec: 1298.94
INFO:tensorflow:loss = 16.887302, step = 8601 (0.078 sec)
INFO:tensorflow:global_step/sec: 1229.53
INFO:tensorflow:loss = 7.3606596, step = 8701 (0.081 sec)
INFO:tensorflow:global_step/sec: 1283.88
INFO:tensorflow:loss = 9.531899, step = 8801 (0.078 sec)
INFO:tensorflow:global_step/sec: 1216.78
INFO:tensorflow:loss = 6.2282705, step = 8901 (0.082 sec)
INFO:tensorflow:global_step/sec: 1139.15
INFO:tensorflow

In [67]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-10-31-22:25:26
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-10-31-22:25:33
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.51980686, global_step = 10000, label/mean = 0.002639266, loss = 16.63382, prediction/mean = -0.00447

In [68]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-10-31-22:25:34
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-10-31-22:25:42
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.4792587, global_step = 10000, label/mean = -0.006225935, loss = 15.336278, prediction/mean = -0.0086

In [69]:
metricas_treinamento

{'average_loss': 0.51980686,
 'label/mean': 0.002639266,
 'loss': 16.63382,
 'prediction/mean': -0.0044750753,
 'global_step': 10000}

In [70]:
metricas_teste

{'average_loss': 0.4792587,
 'label/mean': -0.006225935,
 'loss': 15.336278,
 'prediction/mean': -0.008654546,
 'global_step': 10000}

In [71]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [72]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [73]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [74]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [75]:
previsoes

<generator object Estimator.predict at 0x1a2858f678>

In [76]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-1.0114704], dtype=float32)},
 {'predictions': array([-0.9328798], dtype=float32)},
 {'predictions': array([-0.85428905], dtype=float32)}]

In [78]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmp86d0rc19/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[168758.42]
[197610.52]
[226462.64]
